### ISSUE TITLE
Retry doesn't seem to work always

### ISSUE THREAD

**Issue by JeremyCroff** [intuit/saloon#30]
```2018-06-25T16:42:25.976Z - warn: Error seeding {{guid()}}: Error: Request failed with status code 500
(node:49878) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/Users/jcroff/dev/saloon/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jcroff/dev/saloon/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/jcroff/dev/saloon/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:49878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:49878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by JeremyCroff** [comment]
thoughts:
1. the user implementing the seeder could add a catch block on its invocation
2. or we could internally handle failed promise with a catch block on the seed level
